#include <iostream>
#include <string>
using namespace std;
#define MAXSTACK 10

typedef int ItemType;
typedef struct {
    ItemType Item[MAXSTACK];
    int Count;
} Stack;

void awal(Stack *S) {Add commentMore actions
    S->Count = 0;
}

int penuh(Stack *S){
    return (S->Count == MAXSTACK);
}

int kosong(Stack *S){
    return (S->Count == 0);
}

void pop(Stack *S, ItemType *x) 
    if (kosong(S)) {
        cout << "Stack kosong!" << endl;
    } else {
        --(S->Count);
        *x = S->Item[S->Count];
    }
